-- Recreate order_items table with correct structure
-- Need to drop dependent views first or use CASCADE
DROP TABLE IF EXISTS order_items CASCADE;
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  qty INTEGER NOT NULL DEFAULT 1,
  unit_price_twd INTEGER NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'NORMAL', -- 'NORMAL', 'OUT_OF_STOCK', 'PARTIAL_OOS'
  refund_amount INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add columns for International Shipping and Box Fees
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_fee_intl INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS box_fee INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS box_count INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_number TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_method TEXT;

-- Add hold_id to orders table if it doesn't exist (fixes 400 error in admin orders list)
-- Note: wallet_holds table must exist.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS hold_id BIGINT;
-- Optionally add FK constraint if wallet_holds exists
-- ALTER TABLE orders ADD CONSTRAINT orders_hold_id_fkey FOREIGN KEY (hold_id) REFERENCES wallet_holds(id);

-- Add columns for Order Items status (for Out of Stock handling) - now redundant but kept for safety

-- Add columns for Member Tier if not exists (User mentioned "Update profiles.tier")
-- Check constraints for profiles.tier to allow 'guest', 'retail', 'wholesale', 'vip'
-- ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_tier_check;
-- ALTER TABLE profiles ADD CONSTRAINT profiles_tier_check CHECK (tier IN ('guest', 'retail', 'wholesale', 'vip'));

-- New Requirement: Track if shipping has been paid (Order Level)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_paid BOOLEAN DEFAULT FALSE;

-- New Requirement: Item-level shipping tracking for split shipments
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS shipping_fee_intl INTEGER DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS shipping_fee_domestic INTEGER DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS shipping_paid BOOLEAN DEFAULT FALSE;

-- Additional item-level fields for new shipping logic
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS weight FLOAT DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS box_fee INTEGER DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS shipping_method TEXT; -- 'POST', 'BLACK_CAT', 'CVS', 'WHOLESALE_STORE'
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS member_shipping_code TEXT;

-- Create shipping_settings table
CREATE TABLE IF NOT EXISTS shipping_settings (
  key TEXT PRIMARY KEY,
  value NUMERIC
);

-- Seed default values for shipping settings
INSERT INTO shipping_settings (key, value) VALUES 
('rate_intl_kg', 200),
('rate_dom_post', 80),
('rate_dom_blackcat', 130),
('rate_dom_cvs', 60)
ON CONFLICT DO NOTHING;

-- New Requirement: Shipping Country for International Shipping Rate
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS shipping_country TEXT;

-- Seed new default shipping settings for countries
INSERT INTO shipping_settings (key, value) VALUES 
('rate_intl_kr', 165),
('rate_intl_jp', 220),
('rate_intl_th', 180),
('rate_dom_hsinchu', 0) -- Value to be set by admin, defaulting to 0 or similar logic
ON CONFLICT DO NOTHING;

-- Fix for "Could not find the 'note' column of 'wallet_ledger'"
ALTER TABLE wallet_ledger ADD COLUMN IF NOT EXISTS note TEXT;

-- New Requirement: Item-level Box Count for Domestic Shipping
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS box_count INTEGER DEFAULT 1;

-- New Requirement: Wallet Top-up Requests
CREATE TABLE IF NOT EXISTS wallet_topup_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  amount_twd INTEGER NOT NULL,
  bank_account_last_5 TEXT NOT NULL,
  status TEXT DEFAULT 'PENDING', -- 'PENDING', 'APPROVED', 'REJECTED'
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- New Requirement: Line Link for Top-up/Upgrade settings
ALTER TABLE settings_business_info ADD COLUMN IF NOT EXISTS line_link TEXT;

-- New Requirement: Limited Time Products
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_limited_time BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS limited_time_end TIMESTAMPTZ;
