create table if not exists public.doso_import_sessions (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  target_url text not null,
  status text not null default 'pending' check (status in ('pending', 'running', 'paused', 'completed', 'failed')),
  total_count integer not null default 0 check (total_count >= 0),
  processed_count integer not null default 0 check (processed_count >= 0),
  imported_count integer not null default 0 check (imported_count >= 0),
  skipped_count integer not null default 0 check (skipped_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  last_checkpoint_product_code text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.doso_import_items (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.doso_import_sessions(id) on delete cascade,
  product_code text not null,
  status text not null default 'pending' check (status in ('pending', 'running', 'imported', 'skipped_existing', 'failed')),
  reason text,
  payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, product_code)
);

create index if not exists idx_doso_import_sessions_status_created_at
  on public.doso_import_sessions (status, created_at desc);

create index if not exists idx_doso_import_items_session_id_status
  on public.doso_import_items (session_id, status);

create or replace function public.recompute_doso_import_session_counters(p_session_id bigint)
returns table (
  id bigint,
  status text,
  total_count integer,
  processed_count integer,
  imported_count integer,
  skipped_count integer,
  failed_count integer,
  last_checkpoint_product_code text,
  error_message text
)
language sql
as $$
  with stats as (
    select
      count(*) filter (where di.status in ('pending', 'running'))::integer as pending_count,
      count(*) filter (where di.status = 'imported')::integer as imported_count,
      count(*) filter (where di.status = 'skipped_existing')::integer as skipped_count,
      count(*) filter (where di.status = 'failed')::integer as failed_count
    from public.doso_import_items di
    where di.session_id = p_session_id
  ),
  checkpoint as (
    select di.product_code
    from public.doso_import_items di
    where di.session_id = p_session_id
      and di.status in ('imported', 'skipped_existing', 'failed')
    order by di.id desc
    limit 1
  ),
  updated as (
    update public.doso_import_sessions ds
    set
      total_count = s.pending_count + s.imported_count + s.skipped_count + s.failed_count,
      processed_count = s.imported_count + s.skipped_count + s.failed_count,
      imported_count = s.imported_count,
      skipped_count = s.skipped_count,
      failed_count = s.failed_count,
      last_checkpoint_product_code = coalesce((select product_code from checkpoint), ds.last_checkpoint_product_code),
      updated_at = now()
    from stats s
    where ds.id = p_session_id
    returning ds.id, ds.status, ds.total_count, ds.processed_count, ds.imported_count, ds.skipped_count, ds.failed_count, ds.last_checkpoint_product_code, ds.error_message
  )
  select * from updated;
$$;

create or replace function public.claim_doso_import_pending_items(p_session_id bigint, p_limit integer default 20)
returns table (
  id bigint,
  session_id bigint,
  product_code text,
  status text,
  reason text,
  payload jsonb
)
language sql
as $$
  with candidate as (
    select di.id
    from public.doso_import_items di
    where di.session_id = p_session_id
      and (
        di.status = 'pending'
        or (
          di.status = 'running'
          and di.updated_at < now() - interval '10 minutes'
        )
      )
    order by di.id asc
    for update skip locked
    limit greatest(p_limit, 1)
  )
  update public.doso_import_items di
  set
    status = 'running',
    updated_at = now()
  where di.id in (select id from candidate)
  returning di.id, di.session_id, di.product_code, di.status, di.reason, di.payload;
$$;
