-- Create order_items table if not exists
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  qty INTEGER NOT NULL DEFAULT 1,
  unit_price_twd INTEGER NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'NORMAL', -- 'NORMAL', 'OUT_OF_STOCK', 'PARTIAL_OOS'
  refund_amount INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add columns for International Shipping and Box Fees
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_fee_intl INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS box_fee INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS box_count INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_number TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_method TEXT;

-- Add columns for Order Items status (for Out of Stock handling) - now redundant but kept for safety

-- Add columns for Member Tier if not exists (User mentioned "Update profiles.tier")
-- Check constraints for profiles.tier to allow 'guest', 'retail', 'wholesale'
-- ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_tier_check;
-- ALTER TABLE profiles ADD CONSTRAINT profiles_tier_check CHECK (tier IN ('guest', 'retail', 'wholesale', 'vip'));
