-- Add columns for International Shipping and Box Fees
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_fee_intl INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS box_fee INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS box_count INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_number TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_method TEXT;

-- Add columns for Order Items status (for Out of Stock handling)
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'NORMAL'; -- 'NORMAL', 'OUT_OF_STOCK'
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS refund_amount INTEGER DEFAULT 0;

-- Add columns for Hot Products if not exists (mentioned in requirements)
CREATE TABLE IF NOT EXISTS hot_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id)
);

-- OR if using a flag on products table (User mentioned "Select one implementation")
-- ALTER TABLE products ADD COLUMN IF NOT EXISTS is_hot BOOLEAN DEFAULT false;

-- Add columns for Member Tier if not exists (User mentioned "Update profiles.tier")
-- Check constraints for profiles.tier to allow 'guest', 'retail', 'wholesale'
-- ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_tier_check;
-- ALTER TABLE profiles ADD CONSTRAINT profiles_tier_check CHECK (tier IN ('guest', 'retail', 'wholesale', 'vip'));
